on:
  release:
    types: [created, edited]

jobs:
  release_html:
    runs-on: ubuntu-latest
    steps:
      - name: download HTML5
        id: download-html
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "latest"
          file: HTML.zip
          token: "${{ secrets.EXPORT_GITHUB_TOKEN }}"
      - name: deploy to itch.io (HTML5)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html
          ITCH_GAME: just-a-clock
          ITCH_USER: docmccoy
          PACKAGE: HTML.zip
          VERSION: ${{ steps.download-html.outputs.version }}
